monitoring/urls.py
from django.urls import path
from . import views

app_name = "monitoring"
urlpatterns = [
    path('', views.FollowUpListView.as_view(), name='index'),
    path('<int:pk>/', views.FollowUpDetailView.as_view(), name='detail'),
    path('fillout/', views.fillout, name='fillout'),
    path('submit/', views.submit, name='submit')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('monitoring/' , include("monitoring.urls"))
]

monitoring/models.py
from django.db import models
from django.contrib.auth.models import User

class FollowUp(models.Model):
        user = models.ForeignKey(User, on_delete=models.CASCADE)
        activity = models.CharField(max_length=200)

        def __str__(self):
            return str(self.user) + ': ' + self.activity

monitoring/views.py
from django.shortcuts import render, reverse
from .models import FollowUp
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.views import generic

class FollowUpListView(generic.ListView):
    model = FollowUp

class FollowUpDetailView(generic.DetailView):
    model = FollowUp

def fillout(request):
    return render(request, "monitoring/followup_form.html", {})

def submit(request):
    user = User.objects.all()[0]
    try:
        selected_act = request.POST['activity_type']
    except (KeyError):
        return render(request, 'monitoring/fillout.html', {'error_msg': "Veuillez selectionner une activité"})
    else:
        fiche = FollowUp(user=user, activity=selected_act)
        fiche.save()
        return HttpResponseRedirect(reverse('monitoring:detail', args=(fiche.id, )))

monitoring/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'monitoring/styles.css' %}">
    <title>{% block title %}My amazing site{% endblock %}</title>
</head>

<body>
    <div id="sidebar">
        {% block sidebar %}
        <ul>
            <li><a href="/monitoring/">Liste des fiches</a></li>
            <li><a href="/monitoring/fillout/">Remplir une fiche</a></li>
        </ul>
        {% endblock %}
    </div>

    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

monitoring/templates/monitoring/followup_detail.html
{% extends "base.html" %}

{% block content %}
    <h2>Fiche de suivie {{ object.id }}</h2>
    {{ object }}
{% endblock %}

monitoring/templates/monitoring/followup_form.html
{% extends "base.html" %}

{% block content %}
    <h2>Remplir une fiche de suivie</h2>
    <form action="{% url 'monitoring:submit' %}" method="post">
        {% csrf_token %}
        <fieldset>
            {% if error_msg %}<p><strong>{{error_msg}}</p></strong>{% endif %}
            <input type='text' id='activity_type' name='activity_type' />
        </fieldset>
        <input type='submit' value='Submit' />
    </form>
{% endblock %}

monitoring/templates/monitoring/followup_list.html
{% extends "base.html" %}

{% block content %}
    <h2>Liste des fiches de suivie</h2>
    <ul>
        {% for followUp in object_list %}
            <a href="{% url 'monitoring:detail' followUp.id %}"><li>{{ followUp }}</li></a>
        {% endfor %}
    </ul>
{% endblock %}